version: 2    # This version is mandatory

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: "requirements.txt"
    - method: pip
  system_packages: true

sphinx:
  fail_on_warning: true

formats:
  - pdf
  - epub
  - htmlzip
